"use client";

import React, { useEffect, useState, useRef } from "react";
import { Terminal, Users, Cpu, ShieldAlert } from "lucide-react";

interface StatItem {
  targetNum: number;
  suffix: string;
  label: string;
  subLabel: string;
}

const STATS_DATA: StatItem[] = [
  {
    targetNum: 500,
    suffix: "+",
    label: "PROJECTS COMPLETED",
    subLabel: "Fully synthesized creative deliverable packages dispatching on time."
  },
  {
    targetNum: 100,
    suffix: "+",
    label: "HAPPY CLIENTS",
    subLabel: "Corporate partners, automotive lines, and startups scaling globally."
  },
  {
    targetNum: 10,
    suffix: "M+",
    label: "CONTENT VIEWS",
    subLabel: "Cumulative consumer views generated by synthesized campaigns."
  },
  {
    targetNum: 99,
    suffix: "%",
    label: "CLIENT SATISFACTION",
    subLabel: "High retention score, reflecting absolute visual style perfection."
  }
];

export default function Stats() {
  const [counts, setCounts] = useState<number[]>([0, 0, 0, 0]);
  const sectionRef = useRef<HTMLDivElement>(null);
  const [hasScrolledIn, setHasScrolledIn] = useState(false);

  useEffect(() => {
    const currentRef = sectionRef.current;
    const observer = new IntersectionObserver(
      (entries) => {
        const [entry] = entries;
        if (entry.isIntersecting) {
          setHasScrolledIn(true);
        }
      },
      { threshold: 0.2 }
    );

    if (currentRef) {
      observer.observe(currentRef);
    }

    return () => {
      if (currentRef) {
        observer.unobserve(currentRef);
      }
    };
  }, []);

  useEffect(() => {
    if (!hasScrolledIn) return;

    const intervals = STATS_DATA.map((stat, idx) => {
      const duration = 1500; // 1.5s animation duration
      const steps = 40;
      const stepDuration = duration / steps;
      let currentStep = 0;
      
      const interval = setInterval(() => {
        currentStep++;
        const progress = currentStep / steps;
        const currentCount = Math.floor(progress * stat.targetNum);
        
        setCounts(prev => {
          const next = [...prev];
          next[idx] = currentCount;
          return next;
        });

        if (currentStep >= steps) {
          setCounts(prev => {
            const next = [...prev];
            next[idx] = stat.targetNum;
            return next;
          });
          clearInterval(interval);
        }
      }, stepDuration);

      return interval;
    });

    return () => {
      intervals.forEach(interval => interval && clearInterval(interval));
    };
  }, [hasScrolledIn]);

  return (
    <section ref={sectionRef} className="py-20 bg-black px-6 border-t border-zinc-900 relative overflow-hidden font-sans-custom">
      <div className="absolute top-1/2 left-0 w-[200px] h-[200px] bg-red-600/5 rounded-full blur-[100px] pointer-events-none" />

      <div className="max-w-7xl mx-auto relative z-10-custom">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {STATS_DATA.map((item, idx) => (
            <div
              key={idx}
              className="p-6 bg-zinc-900/20 border border-zinc-850 rounded-xl hover:border-red-600/25 transition-all duration-300 relative group overflow-hidden"
            >
              {/* Stat number */}
              <div className="space-y-2">
                <span className="text-3xl md:text-5xl font-display-custom font-black text-white font-mono-custom tracking-tight flex items-baseline">
                  {counts[idx]}
                  <span className="text-red-600 font-mono-custom">{item.suffix}</span>
                </span>
                
                <h4 className="text-xs font-mono-custom text-zinc-300 uppercase tracking-widest font-extrabold block">
                  {item.label}
                </h4>

                <p className="text-zinc-500 text-[10px] sm:text-[11px] leading-relaxed font-sans-custom pt-1">
                  {item.subLabel}
                </p>
              </div>

              {/* Glowing back element on hover */}
              <div className="absolute inset-x-0 bottom-0 h-[2px] bg-red-600 scale-x-0 group-hover:scale-x-100 transition-transform duration-300 origin-left" />
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
