"use client";

import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Star, ChevronLeft, ChevronRight, Quote, ShieldCheck } from "lucide-react";
import Image from "next/image";

interface Testimonial {
  name: string;
  role: string;
  company: string;
  quote: string;
  rating: number;
  imageUrl: string;
}

const TESTIMONIALS_DATA: Testimonial[] = [
  {
    name: "Kaelen Mercer",
    role: "VP of Product Development",
    company: "VESSEL ELECTRIC VEHICLES",
    quote: "AXON CREATIVE LAB completely transformed our brand identity. The virtual commercial video they synthesized exceeded all internal metrics, pulling over 10M organic impressions without real shooting budgets.",
    rating: 5,
    imageUrl: "https://picsum.photos/seed/kaelen/150/150"
  },
  {
    name: "Sienna Pierce",
    role: "Creative Brand Strategy Lead",
    company: "AETHERIS COSMETICS",
    quote: "The brand guidelines, geometry formulas, and vector styles generated by AXON's core systems feel fresh and luxurious. We had our entire global packaging framework delivered in 48 hours. Absolute game-changer.",
    rating: 5,
    imageUrl: "https://picsum.photos/seed/sienna/150/150"
  },
  {
    name: "Vikram Shenoy",
    role: "Managing Director of Acquisitions",
    company: "SYNAPSE WATCHMAKERS",
    quote: "The interactive zero-gravity product visuals generated for our high-end carbon timepiece line yielded 4.2x engagement improvements in early testing. Deep planning plus meticulous AI-powered visuals builds absolute customer trust.",
    rating: 5,
    imageUrl: "https://picsum.photos/seed/vikram/150/150"
  },
  {
    name: "Elena Rostova",
    role: "Head of Marketing and Lead Capture",
    company: "LUMINA ACTIVEWEAR",
    quote: "Stunning rendering speeds and outstanding AI music production tracks customized for our digital commercials. No licensed audio copyright hassles—just pure premium brand assets that convert visitors instantly.",
    rating: 5,
    imageUrl: "https://picsum.photos/seed/elena/150/150"
  }
];

export default function Testimonials() {
  const [activeIndex, setActiveIndex] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => {
      setActiveIndex((prev) => (prev + 1) % TESTIMONIALS_DATA.length);
    }, 8000);
    return () => clearInterval(timer);
  }, []);

  const handlePrev = () => {
    setActiveIndex((prev) => (prev - 1 + TESTIMONIALS_DATA.length) % TESTIMONIALS_DATA.length);
  };

  const handleNext = () => {
    setActiveIndex((prev) => (prev + 1) % TESTIMONIALS_DATA.length);
  };

  return (
    <section className="py-24 bg-zinc-950 px-6 relative border-t border-zinc-900 overflow-hidden font-sans-custom">
      
      {/* Red accent glow */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[350px] h-[350px] bg-red-600/5 rounded-full blur-[120px] pointer-events-none" />

      <div className="max-w-4xl mx-auto space-y-12 relative z-10 select-none">
        
        {/* Header Title Grid */}
        <div className="text-center space-y-4">
          <span className="font-mono-custom text-[10px] text-red-500 font-bold uppercase tracking-widest border border-red-500/10 bg-red-500/5 px-2.5 py-1 rounded-sm">
            04. WHAT CLIENTS SAY
          </span>
          <h2 className="text-3xl md:text-5xl font-display-custom font-black uppercase text-white tracking-widest">
            CONGLOMERATE RECOGNITIONS
          </h2>
        </div>

        {/* Testimonial Active Display Deck */}
        <div className="relative min-h-[300px] md:min-h-[250px] flex items-center justify-center">
          <AnimatePresence mode="wait">
            <motion.div
              key={activeIndex}
              initial={{ opacity: 0, x: 25 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -25 }}
              transition={{ duration: 0.5 }}
              className="w-full bg-zinc-900/40 rounded-2xl border border-zinc-850 p-6 md:p-8 flex flex-col md:flex-row items-center gap-6 md:gap-8 relative overflow-hidden"
            >
              {/* Profile image with red boundary circular frame */}
              <div className="relative shrink-0 w-20 h-20 md:w-24 md:h-24 rounded-full border border-red-500/30 overflow-hidden glow-red-sm">
                <Image
                  src={TESTIMONIALS_DATA[activeIndex].imageUrl}
                  alt={TESTIMONIALS_DATA[activeIndex].name}
                  fill
                  referrerPolicy="no-referrer"
                  sizes="(max-w-768px) 80px, 96px"
                  className="object-cover"
                />
              </div>

              {/* Text, name and star reviews */}
              <div className="flex-1 space-y-4 text-center md:text-left">
                <div className="flex items-center justify-center md:justify-start gap-1">
                  {[...Array(TESTIMONIALS_DATA[activeIndex].rating)].map((_, i) => (
                    <Star key={i} className="w-3.5 h-3.5 fill-red-600 text-red-600" />
                  ))}
                </div>

                {/* Testimonial Quote */}
                <p className="text-zinc-300 text-xs md:text-sm font-sans-custom leading-relaxed relative italic">
                  &ldquo;{TESTIMONIALS_DATA[activeIndex].quote}&rdquo;
                </p>

                {/* Client Profile details */}
                <div className="pt-2 border-t border-white/5 flex flex-col md:flex-row md:items-center justify-between gap-2">
                  <div>
                    <h4 className="text-white text-xs uppercase font-mono-custom font-extrabold tracking-widest">
                      {TESTIMONIALS_DATA[activeIndex].name}
                    </h4>
                    <p className="text-[10px] text-zinc-500 font-mono-custom uppercase tracking-wider mt-0.5">
                      {TESTIMONIALS_DATA[activeIndex].role} &ndash;{" "}
                      <strong className="text-red-500">{TESTIMONIALS_DATA[activeIndex].company}</strong>
                    </p>
                  </div>
                  <div className="hidden md:flex items-center gap-1 text-[10px] font-mono-custom text-zinc-500 uppercase tracking-widest bg-zinc-950 p-1.5 px-3 rounded border border-zinc-900">
                    <ShieldCheck className="w-3.5 h-3.5 text-red-600" />
                    <span>SECURED TESTIMONIAL</span>
                  </div>
                </div>
              </div>

              <Quote className="absolute -top-3 -right-3 w-16 h-16 text-white/5 select-none pointer-events-none" />
            </motion.div>
          </AnimatePresence>
        </div>

        {/* Carousel indicators & Manual clickers */}
        <div className="flex items-center justify-between pt-2 border-t border-white/5">
          <div className="flex items-center gap-1.5">
            {TESTIMONIALS_DATA.map((_, idx) => (
              <button
                key={idx}
                onClick={() => setActiveIndex(idx)}
                className={`h-1 rounded-full transition-all cursor-pointer ${
                  activeIndex === idx ? "w-6 bg-red-600" : "w-2 bg-zinc-800"
                }`}
                title={`Swipe review Card ${idx + 1}`}
              />
            ))}
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrev}
              className="p-2 border border-zinc-850 hover:border-white rounded-md bg-zinc-900/50 text-zinc-400 hover:text-white transition-all cursor-pointer"
              title="Previous testimonial"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            <button
              onClick={handleNext}
              className="p-2 border border-zinc-850 hover:border-white rounded-md bg-zinc-900/50 text-zinc-400 hover:text-white transition-all cursor-pointer"
              title="Next testimonial"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>

      </div>
    </section>
  );
}
